In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [21]:
dataset=pd.read_csv('/content/drive/MyDrive/MLB-LAB/Dataset/Bank_data.csv')
data=dataset

In [22]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [23]:
x=data.iloc[:,3:13].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [24]:
y=data.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0])

In [25]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
x[:,1]=encoder.fit_transform(x[:,1])

In [26]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
x[:,2]=encoder.fit_transform(x[:,2])

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [29]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [30]:
classifier=Sequential()

In [31]:
classifier.add(Dense(units=2, kernel_initializer='uniform',activation='relu',input_dim=10))

In [32]:
classifier.add(Dense(units=2,kernel_initializer='uniform',activation='relu'))

In [33]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [34]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
classifier.fit(x_train,y_train,batch_size=10,epochs=10)

Epoch 1/10
750/750 [==============================] - 6s 6ms/step - loss: 0.6169 - accuracy: 0.7952
Epoch 2/10
750/750 [==============================] - 3s 4ms/step - loss: 0.5376 - accuracy: 0.7963
Epoch 3/10
750/750 [==============================] - 3s 3ms/step - loss: 0.5132 - accuracy: 0.7963
Epoch 4/10
750/750 [==============================] - 2s 3ms/step - loss: 0.5071 - accuracy: 0.7963
Epoch 5/10
750/750 [==============================] - 2s 3ms/step - loss: 0.5058 - accuracy: 0.7963
Epoch 6/10
750/750 [==============================] - 4s 5ms/step - loss: 0.5056 - accuracy: 0.7963
Epoch 7/10
750/750 [==============================] - 3s 4ms/step - loss: 0.5056 - accuracy: 0.7963
Epoch 8/10
750/750 [==============================] - 3s 4ms/step - loss: 0.5056 - accuracy: 0.7963
Epoch 9/10
750/750 [==============================] - 3s 4ms/step - loss: 0.5056 - accuracy: 0.7963
Epoch 10/10
750/750 [==============================] - 2s 3ms/step - loss: 0.5056 - accuracy: 0.7963

In [36]:
y_pred=classifier.predict(x_test)
y_pred

79/79 [==============================] - 1s 3ms/step


array([[0.20401444],
       [0.20401444],
       [0.20401444],
       ...,
       [0.20401444],
       [0.20401444],
       [0.20401444]], dtype=float32)

In [40]:
y_pred=y_pred>0.5
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [42]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1991,    0],
       [ 509,    0]])

In [44]:
from sklearn import metrics
prediction=metrics.accuracy_score(y_test,y_pred)
print("accuracy",prediction*100,"%")

accuracy 79.64 %
