
To check if customer exited or not-> ANN can consider all the features at once. But not other algorithms that we studied earlier.

In [1]:
import numpy as np #importing the libraries(step-2)
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Here first 3 columns are not that important to decide if the customer exited or not. [:,3:13]->independent variables. [:,13]->dependent variable. "tenure" refers to the period of time for which an individual holds a particular financial product or service, such as a loan, fixed deposit, or insurance policy



In [3]:
dataset =pd.read_csv("drive/My Drive/MLB-LAB/heart_failure_clinical_records_dataset.csv") #importing the dataset(step-3)
data=dataset
data

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

In [4]:
X=data.iloc[:,0:12].values #independent variale-X ->if .values is removed proper two columns are printed.But with .values it prints as an array.
X

array([[7.500e+01, 0.000e+00, 5.820e+02, ..., 1.000e+00, 0.000e+00,
        4.000e+00],
       [5.500e+01, 0.000e+00, 7.861e+03, ..., 1.000e+00, 0.000e+00,
        6.000e+00],
       [6.500e+01, 0.000e+00, 1.460e+02, ..., 1.000e+00, 1.000e+00,
        7.000e+00],
       ...,
       [4.500e+01, 0.000e+00, 2.060e+03, ..., 0.000e+00, 0.000e+00,
        2.780e+02],
       [4.500e+01, 0.000e+00, 2.413e+03, ..., 1.000e+00, 1.000e+00,
        2.800e+02],
       [5.000e+01, 0.000e+00, 1.960e+02, ..., 1.000e+00, 1.000e+00,
        2.850e+02]])

In [5]:
Y=data.iloc[:,12].values
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
X=X[:,1:]
X

array([[0.000e+00, 5.820e+02, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        4.000e+00],
       [0.000e+00, 7.861e+03, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        6.000e+00],
       [0.000e+00, 1.460e+02, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        7.000e+00],
       ...,
       [0.000e+00, 2.060e+03, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        2.780e+02],
       [0.000e+00, 2.413e+03, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        2.800e+02],
       [0.000e+00, 1.960e+02, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        2.850e+02]])

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [14]:
#As we are using large number of inputs-> to avoid scaling difference or to take data to same scale we use standard scalar
#Generally if we have attributes with one value and other with varying value it helps to scale to a single value which will be in same range.
from sklearn.preprocessing import StandardScaler #when numbers are in two  different levels-we use Standard Scaler to normalize data here age and salary
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [15]:
X_test

array([[ 1.1201415 , -0.47902153, -0.84091787,  0.19723428, -0.76340124,
        -0.42516583, -0.59870359,  0.96163666, -1.35839541, -0.68283063,
         0.7417037 ],
       [ 1.1201415 , -0.42805227,  1.18917678,  0.19723428,  1.30992713,
        -0.6775321 , -0.37986111, -0.12761055, -1.35839541, -0.68283063,
         0.547417  ],
       [ 1.1201415 ,  0.41803755, -0.84091787, -0.68386838, -0.76340124,
        -1.33368438, -0.27043986,  0.09023889,  0.73616267, -0.68283063,
        -1.5379269 ],
       [-0.89274435,  0.01130281,  1.18917678, -0.24331705,  1.30992713,
         1.03855848, -0.70812483,  0.74378721, -1.35839541, -0.68283063,
         0.87122817],
       [-0.89274435, -0.34548205, -0.84091787, -0.68386838, -0.76340124,
        -0.96018231, -0.16101862, -0.99900832,  0.73616267, -0.68283063,
         1.03960997],
       [ 1.1201415 , -0.52183571,  1.18917678,  1.95943958, -0.76340124,
        -0.97027696, -0.48928235,  0.09023889, -1.35839541, -0.68283063,
        -0.294

**NOW LET'S MAKE ANN**

In [16]:
import keras #for deep nural networks
from keras.models import Sequential #feed forward network
from keras.layers import Dense #fully-connected->each and every node is connected to all the nodes in next layer

In [17]:
#Initializing the ANN
classifier=Sequential()

In [18]:
#Adding the input layer and first hidden layer->
# input layer has 11 input so to decide the nodes in hidden layer->1.hyperparameter tuning 2.units=[3(input)+1(output)/2]
#kernel_initializer-> is the weights- here uniform is given (same random number is assigned)
# activation functions-> 1. relu=rectified linear unit used for all the hidden layer-> gives output either 0 or 1
# 2. sigmoidal-> used for all the output layer->gives probability of values between 0 and 1->either bipolar or binary
# input_dim-> input values
classifier.add(Dense(units=6, kernel_initializer='uniform',activation='relu',input_dim=11))

In [19]:
# Adding second hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform',activation='relu')) #no need to give input again as dense function will take care of the connection

In [20]:
# Add the output layer->for multiple outputs use activation function as softmax
classifier.add(Dense(units=1, kernel_initializer='uniform',activation='sigmoid'))

In [21]:
# Compiling the ANN - adam optimizes weights using Stochastic Gradient Descent -> to reduce error gradually
# loss function for binary classification is binary_crossentropy -> for 1 output
# loss function for multi-class classification model where there are two or more output labels category_crossentropy
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [22]:
# Fitting the ANN to the training set
classifier.fit(X_train,Y_train,batch_size=10,epochs=10)
#Total input=10,000 Training=8,000 ,weight updation is for every batch (how many data points are privided), epoch-> this 8,000 how many times it is repeated

Epoch 1/10
24/24 [==============================] - 2s 3ms/step - loss: 0.6912 - accuracy: 0.6778
Epoch 2/10
24/24 [==============================] - 0s 3ms/step - loss: 0.6866 - accuracy: 0.6946
Epoch 3/10
24/24 [==============================] - 0s 3ms/step - loss: 0.6806 - accuracy: 0.6946
Epoch 4/10
24/24 [==============================] - 0s 3ms/step - loss: 0.6714 - accuracy: 0.6946
Epoch 5/10
24/24 [==============================] - 0s 3ms/step - loss: 0.6560 - accuracy: 0.6946
Epoch 6/10
24/24 [==============================] - 0s 3ms/step - loss: 0.6317 - accuracy: 0.6946
Epoch 7/10
24/24 [==============================] - 0s 3ms/step - loss: 0.5997 - accuracy: 0.6987
Epoch 8/10
24/24 [==============================] - 0s 3ms/step - loss: 0.5604 - accuracy: 0.7280
Epoch 9/10
24/24 [==============================] - 0s 3ms/step - loss: 0.5220 - accuracy: 0.7699
Epoch 10/10
24/24 [==============================] - 0s 4ms/step - loss: 0.4853 - accuracy: 0.7866


In [23]:
Y_pred=classifier.predict(X_test)
Y_pred

2/2 [==============================] - 0s 6ms/step


array([[0.16863747],
       [0.2789182 ],
       [0.51172316],
       [0.21964496],
       [0.23417085],
       [0.21072774],
       [0.5163556 ],
       [0.23087661],
       [0.5235462 ],
       [0.3379364 ],
       [0.2473265 ],
       [0.38393348],
       [0.29252157],
       [0.26549357],
       [0.42753416],
       [0.49477133],
       [0.21873194],
       [0.26166546],
       [0.2652204 ],
       [0.23204246],
       [0.3835797 ],
       [0.46151453],
       [0.49655077],
       [0.48634836],
       [0.3777469 ],
       [0.22968961],
       [0.40314865],
       [0.2058072 ],
       [0.13293448],
       [0.2528326 ],
       [0.20257373],
       [0.5275274 ],
       [0.24798386],
       [0.27380756],
       [0.5199011 ],
       [0.40625745],
       [0.23644504],
       [0.35432404],
       [0.1263838 ],
       [0.53026646],
       [0.11755234],
       [0.39171565],
       [0.2344365 ],
       [0.32122058],
       [0.52025175],
       [0.3434853 ],
       [0.1690038 ],
       [0.141

In [40]:
# As output is sigmoidal -> now predicting the test set results
Y_pred=classifier.predict(X_test)
Y_pred=Y_pred>0.3 #greater than 0.3 is true else false
Y_pred

2/2 [==============================] - 0s 9ms/step


array([[False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True]])

In [41]:
Y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [42]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)
cm

array([[28,  9],
       [ 3, 20]])

In [43]:
from sklearn import metrics
prediction=metrics.accuracy_score(Y_test,Y_pred)
print("accuracy:",prediction *100,"%")

accuracy: 80.0 %
