
To check if customer exited or not-> ANN can consider all the features at once. But not other algorithms that we studied earlier.

In [53]:
import numpy as np #importing the libraries(step-2)
import matplotlib.pyplot as plt
import pandas as pd

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Here first 3 columns are not that important to decide if the customer exited or not. [:,3:13]->independent variables. [:,13]->dependent variable. "tenure" refers to the period of time for which an individual holds a particular financial product or service, such as a loan, fixed deposit, or insurance policy



In [56]:
dataset =pd.read_csv("drive/My Drive/MLB-LAB/Social_Network_Ads.csv") #importing the dataset(step-3)
data=dataset
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [57]:
X=data.iloc[:,1:4].values #independent variale-X ->if .values is removed proper two columns are printed.But with .values it prints as an array.
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [58]:
Y=data.iloc[:,4].values
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [60]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

encoder = LabelEncoder()
X[:,0] = encoder.fit_transform(X[:,0]) #for gender
X

array([[1, 1, 19000],
       [1, 17, 20000],
       [0, 8, 43000],
       ...,
       [0, 32, 20000],
       [1, 18, 33000],
       [0, 31, 36000]], dtype=object)

In [62]:
X=X[:,0:]
X

array([[1, 1, 19000],
       [1, 17, 20000],
       [0, 8, 43000],
       ...,
       [0, 32, 20000],
       [1, 18, 33000],
       [0, 31, 36000]], dtype=object)

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [64]:
#As we are using large number of inputs-> to avoid scaling difference or to take data to same scale we use standard scalar
#Generally if we have attributes with one value and other with varying value it helps to scale to a single value which will be in same range.
from sklearn.preprocessing import StandardScaler #when numbers are in two  different levels-we use Standard Scaler to normalize data here age and salary
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [65]:
X_test

array([[ 1.02532046e+00, -7.98950822e-01,  4.94607583e-01],
       [-9.75304830e-01, -2.12648508e-02, -5.77359062e-01],
       [ 1.02532046e+00, -3.12897090e-01,  1.46942725e-01],
       [-9.75304830e-01, -7.98950822e-01,  2.62831011e-01],
       [-9.75304830e-01, -3.12897090e-01, -5.77359062e-01],
       [ 1.02532046e+00, -1.09058306e+00, -1.44652121e+00],
       [-9.75304830e-01, -7.01740076e-01, -1.59138156e+00],
       [ 1.02532046e+00, -2.15686344e-01,  2.14601566e+00],
       [-9.75304830e-01, -1.96547978e+00, -5.58617754e-02],
       [ 1.02532046e+00,  8.53631867e-01, -7.80163563e-01],
       [ 1.02532046e+00, -7.98950822e-01, -6.06331134e-01],
       [-9.75304830e-01, -9.93372315e-01, -4.32498705e-01],
       [ 1.02532046e+00, -1.18475597e-01, -4.32498705e-01],
       [ 1.02532046e+00,  7.59458956e-02,  2.04886868e-01],
       [ 1.02532046e+00, -1.77105829e+00,  4.65635512e-01],
       [-9.75304830e-01, -6.04529329e-01,  1.36376973e+00],
       [ 1.02532046e+00, -1.18475597e-01

**NOW LET'S MAKE ANN**

In [66]:
import keras #for deep nural networks
from keras.models import Sequential #feed forward network
from keras.layers import Dense #fully-connected->each and every node is connected to all the nodes in next layer

In [67]:
#Initializing the ANN
classifier=Sequential()

In [68]:
#Adding the input layer and first hidden layer->
# input layer has 11 input so to decide the nodes in hidden layer->1.hyperparameter tuning 2.units=[3(input)+1(output)/2]
#kernel_initializer-> is the weights- here uniform is given (same random number is assigned)
# activation functions-> 1. relu=rectified linear unit used for all the hidden layer-> gives output either 0 or 1
# 2. sigmoidal-> used for all the output layer->gives probability of values between 0 and 1->either bipolar or binary
# input_dim-> input values
classifier.add(Dense(units=2, kernel_initializer='uniform',activation='relu',input_dim=3))

In [69]:
# Adding second hidden layer
classifier.add(Dense(units=2, kernel_initializer='uniform',activation='relu')) #no need to give input again as dense function will take care of the connection

In [70]:
# Add the output layer->for multiple outputs use activation function as softmax
classifier.add(Dense(units=1, kernel_initializer='uniform',activation='sigmoid'))

In [71]:
# Compiling the ANN - adam optimizes weights using Stochastic Gradient Descent -> to reduce error gradually
# loss function for binary classification is binary_crossentropy -> for 1 output
# loss function for multi-class classification model where there are two or more output labels category_crossentropy
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [72]:
# Fitting the ANN to the training set
classifier.fit(X_train,Y_train,batch_size=10,epochs=10)
#Total input=10,000 Training=8,000 ,weight updation is for every batch (how many data points are privided), epoch-> this 8,000 how many times it is repeated

Epoch 1/10
32/32 [==============================] - 1s 2ms/step - loss: 0.6920 - accuracy: 0.6219
Epoch 2/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6893 - accuracy: 0.6219
Epoch 3/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6867 - accuracy: 0.6219
Epoch 4/10
32/32 [==============================] - 0s 2ms/step - loss: 0.6830 - accuracy: 0.6219
Epoch 5/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6781 - accuracy: 0.6219
Epoch 6/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6710 - accuracy: 0.6219
Epoch 7/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6619 - accuracy: 0.6219
Epoch 8/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6505 - accuracy: 0.6219
Epoch 9/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6369 - accuracy: 0.6219
Epoch 10/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6219 - accuracy: 0.6219


In [73]:
Y_pred=classifier.predict(X_test)
Y_pred

3/3 [==============================] - 0s 4ms/step


array([[0.38393182],
       [0.39643207],
       [0.39414772],
       [0.3881599 ],
       [0.385043  ],
       [0.33766273],
       [0.3539753 ],
       [0.4523368 ],
       [0.3491376 ],
       [0.4216334 ],
       [0.36196014],
       [0.36869144],
       [0.386256  ],
       [0.41412607],
       [0.3560587 ],
       [0.42654344],
       [0.40495348],
       [0.3528124 ],
       [0.46181604],
       [0.36006907],
       [0.3832878 ],
       [0.46181604],
       [0.41098398],
       [0.4616603 ],
       [0.34002593],
       [0.46181604],
       [0.3872946 ],
       [0.37708998],
       [0.40211496],
       [0.39983007],
       [0.35988772],
       [0.40666792],
       [0.46181604],
       [0.3845719 ],
       [0.35094282],
       [0.3318071 ],
       [0.35859954],
       [0.37819353],
       [0.36479232],
       [0.43499708],
       [0.37623408],
       [0.40182272],
       [0.3827641 ],
       [0.3589302 ],
       [0.45730785],
       [0.3676921 ],
       [0.41759104],
       [0.461

In [95]:
# As output is sigmoidal -> now predicting the test set results
Y_pred=classifier.predict(X_test)
Y_pred=Y_pred>0.45 #greater than 0.45 is true else false
Y_pred

3/3 [==============================] - 0s 6ms/step


array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [

In [96]:
Y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [97]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)
cm

array([[58,  0],
       [ 7, 15]])

In [98]:
from sklearn import metrics
prediction=metrics.accuracy_score(Y_test,Y_pred)
print("accuracy:",prediction *100,"%")

accuracy: 91.25 %
